### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by geekofalltrades** [xanzy/terraform-provider-ciscoasa#5]
Is this provider documented somewhere? If so, can you include a link in the README?

Thanks.

**Comment by svanharmelen** [comment]
@geekofalltrades no, unfortunately this provider isn't documented yet. We are currently using the provider internally as part of a bigger system (called DSFW) which we plan to open source later this year.

Until that time I don't think we are going to add documentation or move this provider to the `terraform-providers` Github org.

But of course you should still be able to play around with the provider by just looking at the schema's defined in the resources. I think they are pretty self describing and should give you a good idea on how to use them.

If you have any specific questions or findings when testing or playing with the provider, I'll be happy to answer them here. So just open a new issue if you stumble upon something you need help with...
